### ISSUE TITLE
bug: multiple `setExtraColumns` calls cause issues with values not being cleared

### ISSUE THREAD

**Issue by rshkabko** [anlutro/laravel-settings#175]
For example, I have multiple user portals. I use `Setting::setExtraColumns(['portal_id' => $portal_id]);`
For example, I want to get (or update) some settings on all portals (or even 2 at once).
\Setting::setExtraColumns(['portal_id' => 15]);
$setting = \Setting::get('EXCHANGE'); // OK, will get portal 15 setting

\Setting::setExtraColumns(['portal_id' => 20]);
$setting = \Setting::get('EXCHANGE'); // BUG, will get portal 15 setting TOO

All because you use here:

`public function load($force = false)
	{
		if (!$this->loaded || $force) {
			$this->data = $this->readData();
            $this->persistedData = $this->data;
            $this->data = array_merge($this->updatedData, $this->data);
            $this->loaded = true;
		}
	}
`

This

`if (!$this->loaded || $force) {`

Please, optimize or remove it.
I hope you understand)

**Comment by rshkabko** [comment]
I spent about 7 hours to understand why my settings are not working))

**Comment by bweston92** [comment]
Hi @rshkabko please correct me if I am wrong but from what I can gather you're using `Setting::setExtraColumns(['portal_id' => $portal_id]);` multiple times in one execution and due to the `load` method using a local cache it overrides the previous values.

This wasn't a use case we had thought about but the following **should** work:

## Option 1

Force reload after changing the columns.

```php
foreach (...) {
    Setting::setExtraColumns(['portal_id' => $portal_id]);
    Setting::load(true);
    ...
}
``` 

## Option 2

Write your own SettingStore that will cater for this, you can do this by extending the base class of the `SettingStore` you currently use and overwriting the function `load`. The custom `SettingStore` can then be configured as your setting store.

## Option 3

Write a PR that resets a `SettingStore`'s state when `setExtraColumns` is called.

**Comment by bweston92** [comment]
Option 3 has been mentioned before https://github.com/anlutro/laravel-settings/issues/32#issuecomment-301100284

Feel free to create a PR or use any other suggested option.

**Comment by rshkabko** [comment]
Hello!
Fixed!
