### ISSUE TITLE
Cast will be helpfull

### ISSUE THREAD

**Issue by cve** [anlutro/laravel-settings#24]
Hi,

for JSON powered APIs the casts like Laravel 5 Eloquent property will be helpful.

**Comment by anlutro** [comment]
It should be possible to just do `return Setting::all()` or `return Setting::get('foo')` from a controller, and because it's an array, Laravel's router should transform it into a JSON response.

It's not really possible for me to do something similar to what Eloquent does in this regard, since the setting store returns arrays or scalar values, not objects.

Or did you have something else in mind?

**Comment by cve** [comment]
I use HTML5 number type input in my UI. Setting value in DB is store as string (varchar), so when I return simple Settings:all() from my route yes it casting to JSON, but I mean casting particular keys to specified types for example setting with key "default_price" => "float". Like $casts property in Eloquent.

**Comment by bweston92** [comment]
Have a layer in front of the settings store that handles it?



—

**Comment by anlutro** [comment]
Ah, I see. I'll think a bit about it but I don't think there's a good way for this library to do what you need.

My initial thought is I suggest you write a class that either extends the setting store, or takes the setting store as a constructor argument, and then you write some wrapper logic that does whatever casting you need.

**Comment by cve** [comment]
Ok, I will do this manually by looping each key and casting... Thanks for your time.
