### ISSUE TITLE
[Suggestion] Fall back to JSON if table does not exist

### ISSUE THREAD

**Issue by selabie68** [anlutro/laravel-settings#57]
Every time I deploy my app I am unable to migrate my database because artisan throws an error saying the settings table does not exist.

It would be good if this automatically fell back to the JSON File Driver if the database table has not yet been created.

**Comment by bweston92** [comment]
Then it would never use the database so just use JSON anyway.

---Sent from Boxer | http://getboxer.com

On 23 August 2016 at 01:07:20 BST, Michael Smith <notifications@github.com> wrote:Every time I deploy my app I am unable to migrate my database because artisan throws an error saying the settings table does not exist.  It would be good if this automatically fell back to the JSON File Driver if the database table has not yet been created.  —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.           {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/anlutro/laravel-settings","title":"anlutro/laravel-settings","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/anlutro/laravel-settings"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"[Suggestion] Fall back to JSON if table does not exist (#57)"}],"action":{"name":"View Issue","url":"https://github.com/anlutro/laravel-settings/issues/57"}}}

**Comment by anarcist69** [comment]
I will re-phrase:

- I have my `config/settings.php` file set to use a database table
- I am ready to deploy my app so I pull it from my repository and go to run `php artisan migrate`
- I get an error that I cannot run `php artisan` because the table `settings` does not exist
- I then have to go and edit my `config/settings.php` file to use the JSON file driver
- Run `php artisan migrate`
- Now my database has the right table `settings`
- I then need to go back to my `config/settings.php` to change it back to using the database driver

Now this is not an issue for already deployed apps, as they will already have the `settings` table.

Although if I am wanting to deploy the app to a new server, it is a lot of hassle.

**Comment by anlutro** [comment]
The real issue seems to me that you're using `Settings::get` before migrations are being ran - i.e. too early in your application lifecycle.
