### ISSUE TITLE
Settings don't seem to persist on Laravel forge scheduled crons. 

### ISSUE THREAD

**Issue by Tapha** [anlutro/laravel-settings#59]
Is there any reason why this would be the case?

**Comment by bweston92** [comment]
That maybe because the save middleware isn't being called.

---Sent from Boxer | http://getboxer.com

On 29 August 2016 at 21:17:21 BST, Tapha Ngum <notifications@github.com> wrote:Is there any reason why this would be the case?  —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.           {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/anlutro/laravel-settings","title":"anlutro/laravel-settings","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/anlutro/laravel-settings"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Settings don't seem to persist on Laravel forge scheduled crons. (#59)"}],"action":{"name":"View Issue","url":"https://github.com/anlutro/laravel-settings/issues/59"}}}

**Comment by Tapha** [comment]
Strange. It seems to work when there are no arguments on the scheduled command. 

For example, this works:

```
//request list
$schedule->command('report:requestlist')->everyTenMinutes();
```

But this doesn't:

```
//Report requests
$schedule->command('reports:request', [
    'reportType' => '_GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_'
])->everyTenMinutes();
```

**Comment by anlutro** [comment]
I don't know anything about the scheduler or forge, but you can try just calling `Settings::save()` manually when you're done setting things.

**Comment by Tapha** [comment]
Just gave that a try. Unfortunately it doesn't seem to resolve the issue.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by bweston92** [comment]
@Tapha - what are you using for storage?

There is several issues that can happen, if another process has it open and writes to it after the cron has written it will obviously over-write.

**Comment by Tapha** [comment]
Turns out I had made the mistake in my $schedule->command(); syntax. My bad guys. 

For reference for the better of others. The correct way to pass an argument to a command in the scheduler is like this: 

`$schedule->command('reports:request _GET_DATA_')->everyTenMinutes();`
