### ISSUE TITLE
Show settings in view and update all changed

### ISSUE THREAD

**Issue by marksie1988** [anlutro/laravel-settings#71]
Hi, I want to show the settings in a view and then have a form submit them all to be updated? 

how would i do this?

**Comment by anlutro** [comment]
Terribly sorry, I completely missed your question.

Maybe you've already figured it out, but basically you do `$settings = Settings:all()`, iterate through them in your view, and then iterate through POST data and set each one using `Settings::set($key, $val)`.

You might want to take some extra steps, such as whitelisting the keys of settings that can be set, so that the end user can't modify the form using chrome inspector or use `curl` to add a bunch of unintended data to your settings.
