### ISSUE TITLE
v0.6.0 - composer.json extra including alias unable to override

### ISSUE THREAD

**Issue by bkuhl** [anlutro/laravel-settings#88]
v.0.6.0 introduced this change into the composer.json:

```
            "extra": {
                "laravel": {
                    "aliases": {
                        "Setting": "anlutro\\LaravelSettings\\Facade"
                    },
                    "providers": [
                        "anlutro\\LaravelSettings\\ServiceProvider"
                    ]
                }
            },
```

This is great for the providers, but the alias is a breaking change and we're unable to override it (that I can find anyways).  

I have my facade alias configured as:

```
'Setting'              => \App\Support\Facades\SettingsManager::class,
```

I then extend this package's `SettingsManager`.  When upgrading to 0.6.0 I see this error:

```
Call to undefined method anlutro\LaravelSettings\DatabaseSettingStore::firstYearDiscount()
```

This is happening because it's using the composer's alias rather than mine.  I think registering the facade should be left optional and removed from composer.json.

Reverting to 0.5.2 resolved the issue.

**Comment by anlutro** [comment]
Hey, technically this is indeed a breaking change but that's what major versions are for. However, I think you're doing something wrong here. Why are you using your own facade? I think the more appropriate way of extending a third-party package is by re-binding the underlying class:

```php
$app->bindShared('anlutro\Settings\SettingsManager', function($app) {
    return new MySettingsManager($app);
});
```

[This page](https://laravel.com/docs/5.0/extending) has some more information. You can also try `Settings::extend` if you want to create a custom driver, that's even cleaner, but might also be a little bit more work.

Regardless - ultimately it might have been a mistake to set a default facade alias. I really can't say, as I don't work with Laravel anymore, but let me know if you're unable to work around this issue.

**Comment by bkuhl** [comment]
I'm extending so that I can use strongly typed parameters and return values.

It's not possible to overwrite that setting when it's in the composer file, so there's no workaround that I could find other than reverting to the previous version, which works sufficiently.

**Comment by anlutro** [comment]
Ah, and the strong typing doesn't work when extending the manager/driver because it's the facade you're calling? I remember there used to be code-generators that generated autocomplete stubs for your facades for use in IDEs like PHPStorm, maybe that can help you out. Honestly, reasons like these are reasons I moved away from using facades at all, and just injected the dependencies directly into my classes' constructors.

I'm tempted to say that the design of Laravel's facades are to blame here, as well as the fact that composer-registered aliases take precedence over user-defined ones. I'm afraid that if I were to remove the default alias now I would probably break the package for more people than I'm helping, but for the next major version (whenever that is) I'm willing to reconsider.

**Comment by bweston92** [comment]
Hi @bkuhl sorry for the inconvenience, I've managed to find a [solution](https://laravel.com/docs/5.5/packages) for you though.

Add the following to your applications composer.json file.

```
"extra": {
    "laravel": {
        "dont-discover": [
            "anlutro/l4-settings"
        ]
    }
},

```

**Comment by bweston92** [comment]
@bkuhl can you confirm the proposed solution worked? If so please create a PR to the README.
